version: '3'
services:
  mariadb:
    image: mariadb:11.0.2
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: popping
      MARIADB_USER: ashe
      MARIADB_PASSWORD: devA509
      MARIADB_ROOT_PASSWORD: test
    volumes:
      - "./mariadb/conf.d:/etc/mysql/conf.d"
      - "./mariadb/data:/var/lib/mysql"
    container_name: mariadb