spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  kakao:
    client:
      id: ${KAKAO_REST_API_KEY}
      secret: ${KAKAO_SECRET_KEY}

  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000