spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: devA509

kakao:
  client:
    id: ${KAKAO_REST_API_KEY}
    secret: ${KAKAO_SECRET_KEY}
    admin : ${KAKAO_ADMIN_KEY}

google:
  client:
    id: ${GOOGLE_API_KEY}
    secret: ${GOOGLE_SECRET_KEY}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        errorDecoder: com.example.SimpleErrorDecoder
        encoder: com.example.SimpleEncoder
token:
  secret: ${JWT_SECRET}
  access-token-expiration-time: 900000 # 15분
  refresh-token-expiration-time: 1209600000 # 2주

logging:
  level:
    org.hibernate.type: trace # 콘솔창에 조건에 바인딩되는 값 및 조회 결과 출력
    com.ashe.popping: debug

