spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/popping
    username: ashe
    password: devA509
  data:
    redis:
      host: redis
      port: 6379
      password: devA509